import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/component/Header";
// _app.js या layout.js में (Next.js version के अनुसार)
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sachin.dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
 ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
